'use client';
import {useEffect,useMemo,useState} from 'react';
const LANGS=[['tr','Türkçe'],['en','English'],['ar','العربية'],['es','Español'],['it','Italiano'],['fr','Français'],['de','Deutsch'],['en-GB','English UK'],['ru','Русский'],['zh','中文']];
const T={
tr:{choose:'Dil seç',chooseDesc:'QasimFlix APK indirme sayfasını hangi dilde kullanmak istersin?',badge:'Android APK',desc:'En güncel QasimFlix Android uygulamasını buradan güvenli şekilde indirebilirsin.',download:'APK indir',noApk:'APK henüz yüklenmedi',version:'Sürüm',size:'Boyut',updated:'Güncellendi',admin:'Admin',language:'Dil',notes:'Güncelleme notları',loading:'Yükleniyor...'},
en:{choose:'Choose language',chooseDesc:'Which language do you want to use on the QasimFlix APK download page?',badge:'Android APK',desc:'Download the latest QasimFlix Android app safely from here.',download:'Download APK',noApk:'APK has not been uploaded yet',version:'Version',size:'Size',updated:'Updated',admin:'Admin',language:'Language',notes:'Update notes',loading:'Loading...'},
ar:{choose:'اختر اللغة',chooseDesc:'ما اللغة التي تريد استخدامها في صفحة تحميل تطبيق QasimFlix؟',badge:'تطبيق أندرويد',desc:'يمكنك تحميل أحدث إصدار من تطبيق QasimFlix للأندرويد بأمان من هنا.',download:'تحميل APK',noApk:'لم يتم رفع ملف APK بعد',version:'الإصدار',size:'الحجم',updated:'آخر تحديث',admin:'لوحة الإدارة',language:'اللغة',notes:'ملاحظات التحديث',loading:'جارٍ التحميل...'},
es:{choose:'Elegir idioma',chooseDesc:'¿En qué idioma quieres usar la página de descarga de QasimFlix APK?',badge:'Android APK',desc:'Descarga de forma segura la última app Android de QasimFlix desde aquí.',download:'Descargar APK',noApk:'Aún no se ha subido el APK',version:'Versión',size:'Tamaño',updated:'Actualizado',admin:'Admin',language:'Idioma',notes:'Notas de actualización',loading:'Cargando...'},
it:{choose:'Scegli lingua',chooseDesc:'In quale lingua vuoi usare la pagina di download di QasimFlix APK?',badge:'Android APK',desc:'Scarica in sicurezza l’ultima app Android di QasimFlix da qui.',download:'Scarica APK',noApk:'APK non ancora caricato',version:'Versione',size:'Dimensione',updated:'Aggiornato',admin:'Admin',language:'Lingua',notes:'Note aggiornamento',loading:'Caricamento...'},
fr:{choose:'Choisir la langue',chooseDesc:'Dans quelle langue veux-tu utiliser la page de téléchargement QasimFlix APK ?',badge:'Android APK',desc:'Télécharge ici la dernière application Android QasimFlix en toute sécurité.',download:'Télécharger APK',noApk:'Aucun APK téléversé',version:'Version',size:'Taille',updated:'Mis à jour',admin:'Admin',language:'Langue',notes:'Notes de mise à jour',loading:'Chargement...'},
de:{choose:'Sprache wählen',chooseDesc:'In welcher Sprache möchtest du die QasimFlix APK-Downloadseite verwenden?',badge:'Android APK',desc:'Lade hier sicher die neueste QasimFlix Android-App herunter.',download:'APK herunterladen',noApk:'APK wurde noch nicht hochgeladen',version:'Version',size:'Größe',updated:'Aktualisiert',admin:'Admin',language:'Sprache',notes:'Update-Hinweise',loading:'Wird geladen...'},
'en-GB':{choose:'Choose language',chooseDesc:'Which language would you like to use for the QasimFlix APK download page?',badge:'Android APK',desc:'Download the latest QasimFlix Android app safely from here.',download:'Download APK',noApk:'The APK has not been uploaded yet',version:'Version',size:'Size',updated:'Updated',admin:'Admin',language:'Language',notes:'Update notes',loading:'Loading...'},
ru:{choose:'Выберите язык',chooseDesc:'На каком языке вы хотите использовать страницу загрузки QasimFlix APK?',badge:'Android APK',desc:'Здесь можно безопасно скачать последнюю версию Android-приложения QasimFlix.',download:'Скачать APK',noApk:'APK ещё не загружен',version:'Версия',size:'Размер',updated:'Обновлено',admin:'Админ',language:'Язык',notes:'Примечания к обновлению',loading:'Загрузка...'},
zh:{choose:'选择语言',chooseDesc:'你想用哪种语言使用 QasimFlix APK 下载页面？',badge:'Android APK',desc:'在这里安全下载最新版 QasimFlix 安卓应用。',download:'下载 APK',noApk:'尚未上传 APK',version:'版本',size:'大小',updated:'更新时间',admin:'管理',language:'语言',notes:'更新说明',loading:'加载中...'}};
function bytes(n){if(!n)return '-';let u=['B','KB','MB','GB'],i=0;n=+n;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
function date(v,l){if(!v)return '-';try{return new Intl.DateTimeFormat(l,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v}}
export default function Home(){const[lang,setLang]=useState('tr'),[ask,setAsk]=useState(false),[apk,setApk]=useState(null),[load,setLoad]=useState(true);const t=useMemo(()=>T[lang]||T.tr,[lang]);useEffect(()=>{const s=localStorage.getItem('qasim_lang');if(s&&T[s])setLang(s);else setAsk(true);fetch('/api/latest',{cache:'no-store'}).then(r=>r.json()).then(d=>setApk(d?.apkUrl?d:null)).catch(()=>setApk(null)).finally(()=>setLoad(false))},[]);function choose(c){setLang(c);localStorage.setItem('qasim_lang',c);setAsk(false)}return <main className="page" dir={lang==='ar'?'rtl':'ltr'}><div className="topbar"><button className="chip" onClick={()=>setAsk(true)}>🌐 {t.language}</button><a className="chip" href="/admin">⚙️ {t.admin}</a></div><section className="card"><div className="hero"><div className="logo-wrap"><img className="logo" src="/qasimflix.png" alt="QasimFlix"/></div><div><div className="kicker">⬇️ {t.badge}</div><h1>Qasim<span>Flix APK</span></h1><p className="desc">{t.desc}</p><div className="meta-grid"><div className="meta"><small>{t.version}</small><strong>{load?t.loading:(apk?.version||'-')}</strong></div><div className="meta"><small>{t.size}</small><strong>{load?t.loading:bytes(apk?.size)}</strong></div><div className="meta"><small>{t.updated}</small><strong>{load?t.loading:date(apk?.publishedAt,lang)}</strong></div><div className="meta"><small>Android</small><strong>APK</strong></div></div><div className="actions">{apk?.downloadUrl||apk?.apkUrl?<a className="btn btn-primary" href={apk.downloadUrl||apk.apkUrl}>⬇️ {t.download}</a>:<button className="btn btn-primary" disabled>{load?t.loading:t.noApk}</button>}<button className="btn btn-soft" onClick={()=>setAsk(true)}>🌐 {t.language}</button></div>{apk?.notes?<div className="notes"><strong>{t.notes}</strong><br/>{apk.notes}</div>:null}</div></div></section>{ask&&<div className="modal-backdrop"><div className="modal"><h2>{t.choose}</h2><p className="desc">{t.chooseDesc}</p><div className="lang-grid">{LANGS.map(([c,l])=><button className="lang-btn" key={c} onClick={()=>choose(c)}>{l}</button>)}</div></div></div>}</main>}
